schema:
  rules:
    configs:
      SqlServerEndpoint:
        type: string
        required: true
        editableBy:
          - OT
      LineHealthEndpoint:
        type: string
        required: true
        editableBy:
          - OT
configs:
  SqlServerEndpoint: http://localhost/SqlServerEndpoint
  LineHealthEndpoint: http://localhost/LineHealthEndpoint
